version: "3.9"

services:
    db:
        build: ./db
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - int-net
    pokemon:
        build: ./pokemon
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/db_dev
            - PORT=8000
        networks:
            - int-net
        depends_on:
            - db
    team:
        build: ./team
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/db_dev
            - PORT=8000
        networks:
            - int-net
        depends_on:
            - db
    reverse-proxy:
        image: nginx:latest
        ports:
            - 8080:8080
        volumes:
            - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
        networks:
            - int-net
        depends_on:
            - pokemon
            - team

networks:
    int-net:
        name: int-net
        external: true
